apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "epay-website.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "epay-website.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  nginx.conf: |-
{{ tpl (.Files.Get "templates/nginx.conf.template") . | nindent 4 }}
