
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "Epay_Website.fullname" . }}-nginx
  labels:
    {{- include "Epay_Website.labels" . | nindent 4 }}
data:
  # Render nginx.conf.template using tpl so values inside template are populated
  nginx.conf: |-
{{ tpl (.Files.Get "nginx.conf.template") . | nindent 4 }}
